/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registro de jugador (lo loguea). */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicio de sesión. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cierra la sesión actual; idempotente. */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jugador de la sesión; refresca el TTL rodante. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            /** Format: date */
            birthdate: string;
            /** @enum {boolean} */
            acceptsTerms: true;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        Player: {
            /** Format: uuid */
            id: string;
            email: string;
            /** Format: date */
            birthdate: string;
            /** Format: date-time */
            createdAt: string;
        };
        Problem: {
            title: string;
            status: number;
            detail: string;
            /** @enum {string} */
            code: "email_taken" | "invalid_credentials" | "underage" | "terms_not_accepted" | "rate_limited" | "validation" | "unauthenticated" | "origin_rejected";
        };
    };
    responses: {
        /** @description Cuerpo inválido → problem+json validation. */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Semántica inválida (menor / términos no aceptados) → problem+json. */
        UnprocessableProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description El correo ya tiene cuenta → problem+json email_taken. */
        EmailTakenProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Credenciales inválidas → problem+json invalid_credentials. */
        InvalidCredentialsProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Presupuesto agotado → problem+json rate_limited + Retry-After. */
        RateLimitedProblem: {
            headers: {
                /** @description Segundos de espera sugeridos. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Sin/inválida/expirada/revocada sesión → problem+json unauthenticated. */
        UnauthenticatedProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Origen no permitido → problem+json origin_rejected. */
        OriginProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Jugador creado; se abre la sesión (cookie). */
            201: {
                headers: {
                    /** @description skyland_session (HttpOnly, Secure, SameSite=Lax, Max-Age 7d). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            403: components["responses"]["OriginProblem"];
            409: components["responses"]["EmailTakenProblem"];
            422: components["responses"]["UnprocessableProblem"];
            429: components["responses"]["RateLimitedProblem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Sesión abierta (cookie). */
            200: {
                headers: {
                    /** @description skyland_session (HttpOnly, Secure, SameSite=Lax, Max-Age 7d). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["InvalidCredentialsProblem"];
            403: components["responses"]["OriginProblem"];
            429: components["responses"]["RateLimitedProblem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cookie borrada (Max-Age=0); 204 aunque la sesión no exista. */
            204: {
                headers: {
                    /** @description skyland_session=; Max-Age=0. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["OriginProblem"];
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Jugador de la sesión. */
            200: {
                headers: {
                    /** @description Re-envío de skyland_session con Max-Age fresco (TTL rodante). */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Player"];
                };
            };
            401: components["responses"]["UnauthenticatedProblem"];
        };
    };
}
