//go:build go1.22

// Package auth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package auth

import (
	"fmt"
	"net/http"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ProblemCode.
const (
	EmailTaken         ProblemCode = "email_taken"
	InvalidCredentials ProblemCode = "invalid_credentials"
	OriginRejected     ProblemCode = "origin_rejected"
	RateLimited        ProblemCode = "rate_limited"
	TermsNotAccepted   ProblemCode = "terms_not_accepted"
	Unauthenticated    ProblemCode = "unauthenticated"
	Underage           ProblemCode = "underage"
	Validation         ProblemCode = "validation"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case EmailTaken:
		return true
	case InvalidCredentials:
		return true
	case OriginRejected:
		return true
	case RateLimited:
		return true
	case TermsNotAccepted:
		return true
	case Unauthenticated:
		return true
	case Underage:
		return true
	case Validation:
		return true
	default:
		return false
	}
}

// Defines values for RegisterRequestAcceptsTerms.
const (
	True RegisterRequestAcceptsTerms = true
)

// Valid indicates whether the value is a known member of the RegisterRequestAcceptsTerms enum.
func (e RegisterRequestAcceptsTerms) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Player defines model for Player.
type Player struct {
	Birthdate openapi_types.Date `json:"birthdate"`
	CreatedAt time.Time          `json:"createdAt"`
	Email     string             `json:"email"`
	Id        openapi_types.UUID `json:"id"`
}

// Problem defines model for Problem.
type Problem struct {
	Code   ProblemCode `json:"code"`
	Detail string      `json:"detail"`
	Status int         `json:"status"`
	Title  string      `json:"title"`
}

// ProblemCode defines model for Problem.Code.
type ProblemCode string

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	AcceptsTerms RegisterRequestAcceptsTerms `json:"acceptsTerms"`
	Birthdate    openapi_types.Date          `json:"birthdate"`
	Email        openapi_types.Email         `json:"email"`
	Password     string                      `json:"password"`
}

// RegisterRequestAcceptsTerms defines model for RegisterRequest.AcceptsTerms.
type RegisterRequestAcceptsTerms bool

// EmailTakenProblem defines model for EmailTakenProblem.
type EmailTakenProblem = Problem

// InvalidCredentialsProblem defines model for InvalidCredentialsProblem.
type InvalidCredentialsProblem = Problem

// OriginProblem defines model for OriginProblem.
type OriginProblem = Problem

// RateLimitedProblem defines model for RateLimitedProblem.
type RateLimitedProblem = Problem

// UnauthenticatedProblem defines model for UnauthenticatedProblem.
type UnauthenticatedProblem = Problem

// UnprocessableProblem defines model for UnprocessableProblem.
type UnprocessableProblem = Problem

// ValidationProblem defines model for ValidationProblem.
type ValidationProblem = Problem

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Inicio de sesión.
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout Cierra la sesión actual; idempotente.
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Me Jugador de la sesión; refresca el TTL rodante.
	// (GET /auth/me)
	Me(w http.ResponseWriter, r *http.Request)
	// Register Registro de jugador (lo loguea).
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Me operation middleware
func (siw *ServerInterfaceWrapper) Me(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Me(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/register", wrapper.Register)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/auth/me", wrapper.Me)

	return m
}
